### ISSUE TITLE
Output type of `QueueClient.result` return does not use generic

### ISSUE THREAD

**Issue by nightgrey** [fal-ai/fal-js#115]
Hey!

Is it correct that the `<Id>` generic in `QueueClient.result` function is unused? Because this way, the output type is `Result<any>` when it could be auto-inferred :)

https://github.com/fal-ai/fal-js/blob/a1c780a601beca98c1a7e587b7df75c43d80273f/libs/client/src/queue.ts#L207-L210

**Current version**
![image](https://github.com/user-attachments/assets/07730035-1157-4cea-b62a-b781a4daf19a)
> Return type is `Result<any>`.

**If <Id> is used**
![image](https://github.com/user-attachments/assets/f403da05-b4a4-4a7f-98cd-2f780255c120)
> Return type is automatically inferred based on the ID, here `Result<FluxLoraOutput>` 

The only change would be...
```diff
- result<Id extends EndpointType>(endpointId: Id, options: BaseQueueOptions): Promise<Result<OutputType<EndpointType>>>;
+ result<Id extends EndpointType>(endpointId: Id, options: BaseQueueOptions): Promise<Result<OutputType<Id>>>;
```

**Comment by drochetti** [comment]
thanks for the detailed report @nightgrey !

I just published `1.2.1` with the fix.
