### ISSUE TITLE
Error on server

### ISSUE THREAD

**Issue by ysj16** [fal-ai/fal-js#118]
I tried executing the code in Node.js, but it returned an error.(I have set credentials in config.)
The workflow is avaible in python.
Could you please help me understand the reason?

node:internal/deps/undici/undici:13484
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13484:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

Node.js v23.4.0

**Comment by ampcpmgp** [comment]
It worked on n8n.

```ts
const { fal } = require("@fal-ai/client");
const fetch = require('cross-fetch');

fal.config({
  fetch,
})
```
