### ISSUE TITLE
error:"no inputs, reconnect when needed!"

### ISSUE THREAD

**Issue by yerled** [fal-ai/fal-js#35]
i send a dataurl as image_url to fal.realtime, then receive a error:
<img width="779" alt="image" src="https://github.com/fal-ai/fal-js/assets/13483247/e5dc5fd1-364f-4400-b674-9afaea402774">

my payload:
<img width="775" alt="image" src="https://github.com/fal-ai/fal-js/assets/13483247/3f6dec52-18d7-4173-b0d8-babd9956befb">

**Comment by drochetti** [comment]
Hi @yerled , that is an expected status when the WS doesn't receive any messages for a given interval determined by the API (usually ~2s), it disconnects. The client will reconnect automatically when you send new messages.

Maybe labeling as an error is misleading here, I'll take this to the team so we can revisit the `status: "error"` in such cases. But don't worry, nothing is wrong. The incoming message right after the one you send is the successful response to your request.
