### ISSUE TITLE
why the background color of the return img   is  black

### ISSUE THREAD

**Issue by duanbaosheng** [fal-ai/fal-js#41]
i  use the  nextjs  example ，It  is  success，but the background color of the return img   is  black
i  do not know  why.
there is  no  other  configs,i see all the documentation

**Comment by drochetti** [comment]
hey @duanbaosheng, could you share which model and what parameters are you using? Usually when the image is fully black, it means it might've hit some sort of "safety check" in the model itself, such as NSFW content.

**Comment by drochetti** [comment]
@duanbaosheng I'll close this issue for now. If you still see an issue with the examples, feel free to re-open or cut another issue.
