### ISSUE TITLE
SvelteKit serverless proxy example?

### ISSUE THREAD

**Issue by phenomen** [fal-ai/fal-js#54]
I'm trying to integrate Fal into SvelteKit app (basically a rewrite of [sdxl-lightning-demo-app](https://github.com/fal-ai/sdxl-lightning-demo-app)) but cannot figure out what exactly should be in the `+server.ts` route file when using 
```js
import { createRequestHandler } from '@fal-ai/serverless-proxy/svelte';
```

**Comment by drochetti** [comment]
Hey @phenomen, thanks for getting in touch. The Svelte docs are missing indeed, I'll work on them soon. In the meantime, feel free to use my sample app as a reference, and also feel free to reach out to me on our Discord:

The repo: https://github.com/drochetti/svelte-app-with-fal

The proxy implementation: https://github.com/drochetti/svelte-app-with-fal/blob/main/src/routes/api/fal/proxy/%2Bserver.ts

**Comment by phenomen** [comment]
@drochetti thanks! It was easy. Just copied your `+server.ts` and everything works perfectly.
