### ISSUE TITLE
Export poll function

### ISSUE THREAD

**Issue by amitrab** [fal-ai/fal-js#59]
It would be great if the js lib would export the poll function, currently defined inside `subscribe()`.
Define it as `poll(requestId)`.
This would allow initiating generation in the backend and polling for it in the client.
This also makes it easy to receive the image in both the client and the backend independently using a webhook.

**Comment by drochetti** [comment]
Hey @amitrab, I addressed this by adding a new API to the queue client:

```
await fal.queue.subscribeToStatus()
```

It accepts some options and can either do polling or streaming. The `fal.subscribe()` uses it behind the scenes. I'll mark this issue as completed, but feel free to reach out again in case you have any other issues and/or feedback.
