### ISSUE TITLE
Doesn't work on server

### ISSUE THREAD

**Issue by ollyde** [fal-ai/fal-js#97]
I want to use this on a standard nodejs server, as it should be because of api keys.

```
    fal.config({
      credentials: env.falApiKey,
    });
    const result = await fal.subscribe('fal-ai/flux-realism', {
      input: {
        prompt: prompt,
      },
      logs: true,
      onQueueUpdate: (update) => {
        if (update.status === 'IN_PROGRESS') {
          update.logs.map((log) => log.message).forEach(console.log);
        }
      },
    });
    console.log(result.data);
    console.log(result.requestId);
```

I get the error

`Your environment does not support fetch. Please provide your own fetch implementation.`

I'm using node-fetch.

**Comment by drochetti** [comment]
Hey @ollyde if you runtime doesn't provide a global `fetch` implementation you need to pass it to the `config()` call.

So you can:

```js
import fetch from 'node-fetch';

fal.config({
  credentials: env.falApiKey,
  fetch,
});
```

**Comment by ollyde** [comment]
@drochetti it was simple. The docker container on the node server was using node 16 not 22.
